//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bugzilla.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bugzilla.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MIMETypes&gt;
        ///  &lt;MIMEType type=&quot;application/andrew-inset&quot; extension=&quot;ez&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/applixware&quot; extension=&quot;aw&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/atom+xml&quot; extension=&quot;atom&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/atomcat+xml&quot; extension=&quot;atomcat&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/atomsvc+xml&quot; extension=&quot;atomsvc&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/ccxml+xml&quot; extension=&quot;ccxml&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/cu-seeme&quot; extension=&quot;cu&quot; /&gt;
        ///  &lt;MIMEType type=&quot;application/davmount+xml&quot; extension=&quot;dav [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIMETypes {
            get {
                return ResourceManager.GetString("MIMETypes", resourceCulture);
            }
        }
    }
}
